### ISSUE TITLE
Fails on Windows 10 - Caused by: java.lang.IllegalStateException: Could not load libeay32.dll

### ISSUE THREAD

**Issue by vishwajeetdusane** [wildfly/wildfly-openssl#16]
tried
`
Caused by: java.lang.IllegalStateException: Could not load libeay32.dll
	at org.wildfly.openssl.SSLImpl.initialize0(Native Method)
	at org.wildfly.openssl.SSLImpl.initialize(SSLImpl.java:33)
	at org.wildfly.openssl.SSL.init(SSL.java:185)
	at org.wildfly.openssl.OpenSSLContextSPI.<init>(OpenSSLContextSPI.java:123)
	at org.wildfly.openssl.OpenSSLContextSPI$OpenSSLTLS_1_0_ContextSpi.<init>(OpenSSLContextSPI.java:441)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.security.Provider$Service.newInstance(Provider.java:1595)
`
Maven Depedency
`    <dependency>
      <groupId>org.wildfly.openssl</groupId>
      <artifactId>wildfly-openssl</artifactId>
      <version>1.0.0.CR5</version>
    </dependency>
`

Usage in Java Code
`
static {
    OpenSSLProvider.register();
  }

...

SSLContext sslContext =  SSLContext.getInstance("openssl.TLSv1");
`

Shouldn't wildfly-openssl dependency does not require to put libeay32 and should be packaged part of the library dependency only ? Any idea why i am getting this error ?

**Comment by vishwajeetdusane** [comment]
OpenSSL library should be provided externally, native JNI binding is packaged only.
