### ISSUE TITLE
How do I set GOST ciphersuites enabled via wildfly?

### ISSUE THREAD

**Issue by beldmit** [wildfly/wildfly-openssl#29]
I need to connect a server supporting Russian GOST ciphersuites.  Russian GOST cryptoalgorithms are supported via engine mechanism. 

I need either call OPENSSL_config or set the OPENSSL_CONF variable pointing on the config file providing engine loading, but then I do not get the connection. 

The stack trace I get is

java.lang.IllegalStateException: WFOPENSSL0012 Failed cipher suite GOST2001-GOST89-GOST89
	at org.wildfly.openssl.OpenSSLEngine.lambda$setEnabledCipherSuites$0(OpenSSLEngine.java:757)
	at org.wildfly.openssl.OpenSSLEngine.initSsl(OpenSSLEngine.java:171)
	at org.wildfly.openssl.OpenSSLEngine.handshake(OpenSSLEngine.java:926)
	at org.wildfly.openssl.OpenSSLEngine.beginHandshakeImplicitly(OpenSSLEngine.java:920)
	at org.wildfly.openssl.OpenSSLEngine.wrap(OpenSSLEngine.java:395)
	at javax.net.ssl.SSLEngine.wrap(SSLEngine.java:469)
	at org.wildfly.openssl.OpenSSLSocket.runHandshake(OpenSSLSocket.java:291)
	at org.wildfly.openssl.OpenSSLSocket.write(OpenSSLSocket.java:486)
	at org.wildfly.openssl.OpenSSLSocket.write(OpenSSLSocket.java:532)
	at org.wildfly.openssl.OpenSSLOutputStream.write(OpenSSLOutputStream.java:51)
	at IdxLib.IdxLib.windlyHttpsClient.writeOutput(windlyHttpsClient.java:154)
	at IdxLib.IdxLib.windlyHttpsClient.connectIDX(windlyHttpsClient.java:99)
	at IdxLib.IdxLib.windlyHttpsClient.testIt(windlyHttpsClient.java:67)
	at IdxLib.IdxLib.windlyHttpsClient.testIt(windlyHttpsClient.java:52)
	at IdxLib.IdxLib.App.main(App.java:31)
Caused by: java.lang.IllegalStateException: error:1410F0B9:SSL routines:SSL_set_cipher_list:no cipher match
	at org.wildfly.openssl.SSLImpl.setCipherSuites0(Native Method)
	at org.wildfly.openssl.SSLImpl.setCipherSuites(SSLImpl.java:428)
	at org.wildfly.openssl.OpenSSLEngine.lambda$setEnabledCipherSuites$0(OpenSSLEngine.java:755)
	... 14 more

openssl s_client -cipher works perfectly.

**Comment by jaikiran** [comment]
@beldmit Did you set the environment variable `OPENSSL_CONF` to point to the configuration file which has these ciphers enabled? And is that environment variable value definitely visible to this process which uses wildfly-openssl? I think if that's setup correctly, then this should work fine.

**Comment by beldmit** [comment]
Yes, I did it. It did not help.
