### ISSUE TITLE
failed tests on clientsessiontest

### ISSUE THREAD

**Issue by jamieb22** [wildfly/wildfly-openssl#45]
LURE! - in org.wildfly.openssl.ClientSessionTest
testJsse(org.wildfly.openssl.ClientSessionTest)  Time elapsed: 0.029 sec  <<< FAILURE!
org.junit.internal.ArrayComparisonFailure: arrays first differed at element [4]; expected:<-40> but was:<16>
	at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:52)
	at org.junit.Assert.internalArrayEquals(Assert.java:414)
	at org.junit.Assert.assertArrayEquals(Assert.java:200)
	at org.junit.Assert.assertArrayEquals(Assert.java:213)
	at org.wildfly.openssl.ClientSessionTest$AssertingHandshakeCompletedListener.handshakeCompleted(ClientSessionTest.java:275)
	at org.wildfly.openssl.OpenSSLSocket.invokeHandshakeListeners(OpenSSLSocket.java:256)
	at org.wildfly.openssl.OpenSSLSocket.runHandshake(OpenSSLSocket.java:360)
	at org.wildfly.openssl.OpenSSLSocket.startHandshake(OpenSSLSocket.java:210)
	at org.wildfly.openssl.ClientSessionTest.testSessionId(ClientSessionTest.java:233)
	at org.wildfly.openssl.ClientSessionTest.testJsse(ClientSessionTest.java:58)

testSessionTimeout(org.wildfly.openssl.ClientSessionTest)  Time elapsed: 0.034 sec  <<< FAILURE!
org.junit.internal.ArrayComparisonFailure: arrays first differed at element [4]; expected:<-36> but was:<-118>
	at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:52)
	at org.junit.Assert.internalArrayEquals(Assert.java:414)
	at org.junit.Assert.assertArrayEquals(Assert.java:200)
	at org.junit.Assert.assertArrayEquals(Assert.java:213)
	at org.wildfly.openssl.ClientSessionTest.testSessionTimeout(ClientSessionTest.java:85)

testSessionSize(org.wildfly.openssl.ClientSessionTest)  Time elapsed: 0.034 sec  <<< FAILURE!
org.junit.internal.ArrayComparisonFailure: arrays first differed at element [4]; expected:<-53> but was:<-39>
	at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:52)
	at org.junit.Assert.internalArrayEquals(Assert.java:414)
	at org.junit.Assert.assertArrayEquals(Assert.java:200)
	at org.junit.Assert.assertArrayEquals(Assert.java:213)
	at org.wildfly.openssl.ClientSessionTest.testSessionSize(ClientSessionTest.java:147)

Running org.wildfly.openssl.SslCiphersTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.018 sec - in org.wildfly.openssl.SslCiphersTest

Results :

Failed tests:
  ClientSessionTest.testJsse:58->testSessionId:233 arrays first differed at element [4]; expected:<-40> but was:<16>
  ClientSessionTest.testSessionTimeout:85 arrays first differed at element [4]; expected:<-36> but was:<-118>
  ClientSessionTest.testSessionSize:147 arrays first differed at element [4]; expected:<-53> but was:<-39>

**Comment by jaikiran** [comment]
@jamieb22 Which version of Java and OpenSSL are you using? Java 1.8 and later enabled "Extended master secret" support recently. OpenSSL 1.0.2 doesn't support that. As a result, you either have to disable it on the Java side by following the instructions here http://www.oracle.com/technetwork/java/javase/8u161-relnotes-4021379.html#JDK-8148421 or you'll have to install and use later versions of OpenSSL 1.1.x which have the extended master secret extension support. In order to run the tests against a specific installation of OpenSSL, you can do as follows:

```
mvn clean install -Dopenssl.path=/usr/local/Cellar/openssl@1.1/1.1.0f/lib/
```
(the value of that property depends on where you have your OpenSSL installation)

**Comment by jamieb22** [comment]
Thanks. I think my question has been answered.

**Comment by jaikiran** [comment]
I have submitted a PR for a better out of the box experience building the project https://github.com/wildfly/wildfly-openssl/pull/47.
